package common

import (
    "io/ioutil"
    "gopkg.in/yaml.v2"
)

// generated by https://mengzhuo.github.io/yaml-to-go/
type T struct {
    Port int `yaml:"port"`
    Secret string `yaml:"secret"`
    Log  struct {
        Level            string   `yaml:"level"`
        Encoding         string   `yaml:"encoding"`
        OutputPaths      []string `yaml:"outputPaths"`
        ErrorOutputPaths []string `yaml:"errorOutputPaths"`
    } `yaml:"log"`
    Gin struct {
        Logfile          string   `yaml:"logfile"`
    } `yaml:"gin"`
	Cluster struct {
	    Namespaces       []string `yaml:"namespaces"`
		Protects         []string `yaml:"protects"`
		Duration         string   `yaml:"duration"`
		IsPrtDep         bool     `yaml:"isPrtDep"`
		IsPrtSingleDep   bool     `yaml:"isPrtSingleDep"`
		IsUptSinglePod   bool     `yaml:"isUptSinglePod"`
	} `yaml:"cluster"`
}

var Config T

func init() {
    content, err := ioutil.ReadFile("conf/chart-server.yaml")
    if err != nil {
        panic("read config file failed")
    }
    err = yaml.Unmarshal(content, &Config)
    if err != nil {
        panic("unmarshal config file failed")
    }
}
